### ISSUE TITLE
Allow simple arithmetic for interval dates

### ISSUE THREAD

**Issue by xymaxim** [xymaxim/ytpb#29]
**Feature description**

There are different ways to specify interval dates: absolute or relative ones. The latest includes: times with the date part [omitted](https://ytpb.readthedocs.io/en/stable/cli.html#time-of-today), [durations](https://ytpb.readthedocs.io/en/stable/cli.html#b-using-duration), and the [date and time replacing components](https://ytpb.readthedocs.io/en/stable/cli.html#date-and-time-replacing-components). However, it's not possible to relatively change the start or end date without modifying another part of the interval.

The ISO 8601 standard assumes some arithmetic (addition, subtraction, etc.) between dates. (Actually, modifying dates by durations is a part of that). For example, the expression `P1DT30S - 20241213T102030` results in `20241212T102000`.

**Use case**

This comes after #27 and the use case described there, but not limited to it.

Here are some potential usage examples.

1. *Download an excerpt between 23:00 and 01:00 every day*:

    ```
    $ ytpb download -i "P1D - 23:00+00/PT2H" ...
    ```

2. *Download two 1h excerpts before some date: one hour and four hours before*:
    
    ```
    $ ytpb download -i "PT1H - 20241213T102030+00/PT1H" ... 
    $ ytpb download -i "PT4H - 20241213T102030+00/PT1H" ... 
     ```

3. *Download an excerpt centered around some moment that happened at 12pm today*:  

    ```
    # (Before)
    $ ytpb download -i 11:55+00/12:05+00 ... 
     ```

    ```
    # (After)
    $ ytpb download -i "PT5M - 12:00+00/12:00+00 + PT5M" ... 
     ```

**Comment by coasterfr** [comment]
yeah this looks good and easy to use too if it isnt too much effort to implement of course, especially 1. by adding "P1D" to make it work for scripts.

**Comment by xymaxim** [comment]
@coasterfr This should work now. Check out the new release [v2024.12.23](https://github.com/xymaxim/ytpb/releases/tag/v2024.12.23). 

> 1. Download an excerpt between 23:00 and 01:00 every day:
>
>     `$ ytpb download -i "P1D - 23:00+00/PT2H" ...`

Note that that was mistaken and wouldn't work. The interval value should be rewritten as `23:00+00 - P1D/PT2H` since only durations can be subtracted from dates or times. Please refer to the [documentation](https://ytpb.readthedocs.io/en/stable/cli.html#date-and-time-arithmetic) for acceptable formats and more examples.

**Comment by coasterfr** [comment]
hi maxim, thanks for your efforts. i tried rewriting the command like you formatted it but seems like it doesn't recognize it ...

ytpb-2024.12.23.exe download -i 22:00+02 - P1D/PT5H A49bKX8gb-8 

im also trying it as written in the documentation:

ytpb-2024.12.23.exe download -i '22:00 - P1D/03:00' A49bKX8gb-8 

a different way of saying download 5 hours worth of footage, but doesnt work. am i doing something wrong...? 

![image](https://github.com/user-attachments/assets/dcdaabf7-2acb-4885-822f-697a91324030)

**Comment by xymaxim** [comment]
As stated in the manual, the option value with whitespace needs to be quoted.

Just tried your two last examples, and it works fine for me on Linux:

```
$ ytpb download -i '22:00 - P1D/03:00' A49bKX8gb-8
Run playback for https://www.youtube.com/watch?v=A49bKX8gb-8
(<<) Collecting info about the video...
```

Could you please try to run the command with double quotes around the interval option, like so: `-i "22:00+02 - P1D/03:00"`?

**Comment by coasterfr** [comment]
ytpb-2024.12.23.exe download -i "22:00 - P1D/03:00" A49bKX8gb-8

works fine on windows with ", not with '. thanks once again!

**Comment by xymaxim** [comment]
Great! I've changed the documentation to reflect this nuance. Thanks a lot for suggesting the feature and testing it out. A small, but quite useful addition.
